name: CI Feature Pipeline

on:
  push:
    branches:
    - "feature/**"
  pull_request:
    branches:
      - "main"

jobs:
  # Linting, formatting and code analysis
  lint:
    uses: ./.github/workflows/reusable/lint_formatting.yml
  # Unit testing
  unit-tests:
    uses: ./.github/workflows/reusable/unit_tests.yml
    needs: lint
